sudo: required
services:
    - docker

before_install:
    - docker build -t giminiani/frontend-with-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true giminiani/frontend-with-docker yarn test